from datetime import datetime
from pathlib import Path


def report_writer(target: str, results: dict, output_dir: str = "reports"):
    Path(output_dir).mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{output_dir}/security_report_{timestamp}.md"

    report = f"""# Security Assessment Report

## Target

{target}

## Generated

{datetime.now().isoformat()}

## Executive Summary

This report was generated by the local AI security agent. It includes safe reconnaissance, configuration checks, crawling results, JavaScript/static asset review, and Nuclei findings.

## Findings Summary

"""

    for section, data in results.items():
        report += f"\n### {section}\n\n"
        report += "```text\n"
        report += str(data)
        report += "\n```\n"

    report += """

## Recommended Next Steps

1. Review missing security headers.
2. Remove placeholder or test references from production pages.
3. Validate external links.
4. Re-run scans after fixes.
5. Manually verify all findings before treating them as confirmed vulnerabilities.

## Notes

This report is intended for authorized security testing only.
"""

    with open(filename, "w") as f:
        f.write(report)

    return {"success": True, "report_file": filename}
